fossology/gsoc

docs/2021/ui/index.md
Added the introduction for fossology UI project.
=> feat(intro-ui): Added the introduction for UI project

docs/2021/copyrights/index.md, docs/2021/copyrights/updates/2021-06-07.md, docs/2021/copyrights/updates/2021-06-15.md, docs/2021/copyrights/updates/2021-06-22.md, docs/2021/copyrights/updates/2021-06-29.md, docs/2021/copyrights/updates/2021-07-05.md
Updated Introduction and Weekly updates for evaluation.
CC: @GMishx
=> Feat: Add Introduction and Weekly Updates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Added the template for pull request and issues.
=> feat(infra): added github infrastructure

docs/2021/ui/updates/aman/2021-06-15.md, docs/2021/ui/updates/aman/2021-06-22.md, docs/2021/ui/updates/aman/2021-06-29.md, docs/2021/ui/updates/aman/2021-07-05.md, docs/2021/ui/updates/aman/2021-07-06.md, docs/2021/ui/updates/aman/2021-07-13.md, docs/2021/ui/updates/aman/_category_.json
Name of the project: React UI
- Added Weekly report from week 1 to week 5
- Fixed my name spelling in Sidebar
=> docs(react-ui): add react ui weekly report

docs/2021/ui/installation.md
React UI
Added the docker installation method to installation guide.
=> feat(installation): added the docker method in installation of ui

docs/2021/buildsystem/first-evaluation.md
Buildsystem and CI/CD
Add first evaluation report
=> feat(buildsystem): add first evaluation report

docs/2021/buildsystem/build.md, docs/2021/buildsystem/updates/2021-06-11.md, docs/2021/buildsystem/updates/2021-06-18.md, docs/2021/buildsystem/updates/2021-06-22.md, docs/2021/buildsystem/updates/2021-06-29.md, docs/2021/buildsystem/updates/2021-07-09.md, docs/2021/buildsystem/updates/2021-07-23.md, docs/2021/buildsystem/updates/2021-07-30.md
Buildsystem
- Add weekly reports for week 5 7 8
- Add more instructions to the build.md
=> docs(buildsystem): add week 5 7 8 reports

docs/2021/copyrights/updates/2021-06-07.md, docs/2021/copyrights/updates/2021-06-15.md, docs/2021/copyrights/updates/2021-06-22.md, docs/2021/copyrights/updates/2021-07-06.md, docs/2021/copyrights/updates/2021-07-13.md, docs/2021/copyrights/updates/2021-07-20.md, docs/2021/copyrights/updates/2021-08-03.md, docs/2021/copyrights/updates/2021-08-10.md
Copyright False Positive
Weekly Updates
=> Update the Weekly updates [Week 7 -Week 9]

docs/2021/minerva/updates/2021-08-17.md
=> Added Week-10 Report

docs/2021/microservice/dockerImages.md, docs/2021/microservice/setup.md, docs/2021/microservice/updates/2021-08-17.md
Making Fossology architecture more microservice friendly
Added week 10 report, setup instructions, and how to build docker images
=> docs(microservices): added week 10 and setup

docs/2021/buildsystem/build.md, docs/2021/buildsystem/final-evaluation.md, docs/2021/buildsystem/index.md, docs/2021/buildsystem/updates/2021-07-23.md, docs/2021/buildsystem/updates/2021-07-30.md, docs/2021/buildsystem/updates/2021-08-06.md, docs/2021/buildsystem/updates/2021-08-13.md
Buildsystem and CI
- Add final evaluation report
- Add week 8 and week 9 report
- Fix minor mistakes
- Update contact info in introduction page
- Update building fossology page
=> docs(buildsystem): add final evaluation report

docs/2022/GSoC-projects.md
gsoc 2022
Update gsoc 2022 idea page
=> docs(/2022): Update gsoc 2022 idea page

package.json, yarn.lock
Update docusaurus to latest `2.0.0-beta.17`
=> feat(docusaurus): update to latest version

docs/2022/GSoC-projects.md
Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>
Idea list for GSoC 2022
Sync with wiki
=> docs(idea-2022): sync with wiki - 20220308

docs/2022/GSoC-projects.md
Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>
Idea list for GSoC 2022
Sync with wiki - 2022/03/16
=> docs(idea-2022): sync with wiki - 20220316

docs/2022/GSoC-projects.md
Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>
Idea list for GSoC 2022
Sync with wiki - 2022/03/23
=> docs(idea-2022): sync with wiki - 20220323

package.json, yarn.lock
Update Docusaurus to latest 2.0.0-beta.21
=> chore(core): update docusaurus to beta 21

docs/2022/atarashi/updates/2022-06-02.md
Atarashi
Community bonding meeting 1 report added
=> feat(atarashi): Add community bonding report

docs/2022/ui/updates/soham/2022-06-02.md
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>
React UI
Weekly update for Community bonding period
PTAL @shaheemazmalmmd @GMishx
=> docs(update): 1st week of communiuty bonding period update provided

docs/2022/ui/updates/ayush/2022-06-02.md
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)
React UI
Weekly update for Community bonding period
=> Update 2022-06-02.md community bonding meetup

docs/2022/reuse/index.md, docs/2022/reuse/updates/2022-06-02.md
Reuse
Weekly update for Community bonding period
=> docs(reuse) : Weekly Update

docs/2022/ui/index.md
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)
ReactUI
Added my linkedin and email in the webiste
=> added linkedin + email in index page

docs/2022/index.md, docs/2022/minutes/02-06-2022.md, static/ics/gsoc_2022_project.ics, static/ics/gsoc_2022_reuse.ics, static/ics/gsoc_2022_spasht.ics
2022 index
Add meeting schedule and calendars for 3 projects:
- REUSE
- Spasht
- Project concept
=> docs(meetings): add meeting schedules for 3 projects

docs/2022/ui/updates/krishna/2022-06-02.md
React UI
Community Bonding Meeting 1 updates added.
=> docs(ReactUI): Updates for meeting 1

docs/2022/reuse/updates/2022-06-02.md
Reuse
Reuse project meeting update added
=> reuse: meeting 2 update

docs/2022/atarashi/updates/2022-06-02.md
Atarashi
Community bonding meeting 2 report added
=> Update community bonding meeting 2 report

docs/2022/ui/updates/samuel/2022-06-02.md
Fossology/Gsoc
-  weekly update
=> Meeting 1 updates

docs/2022/ui/updates/soham/2022-06-02.md
React UI
Weekly Update for the 2nd week of the community bonding period.
@shaheemazmalmmd  @GMishx  PTAL
=> update(docs): 2nd week of community bonding period updates provided

docs/2022/atarashi/index.md, docs/2022/atarashi/updates/2022-06-13.md
=> upadate(docs) Add week 1 update

docs/2022/reuse/updates/2022-06-02.md, docs/2022/reuse/updates/2022-06-13.md
=> docs(reuse): updates of weekly meeting

docs/2022/ui/updates/samuel/2022-06-02.md
updates on the week-2 of community bonding
=> update(docs): updates on the week-2 of community bonding

docs/2022/atarashi/updates/2022-06-20.md
=> upadate(docs):  Add week 2 update

docs/2022/reuse/updates/2022-06-20.md
=> docs(reuse): meeting update

docs/2022/minutes/23-06-2022.md
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Add meeting minutes of 23-06-2022
=> feat(meetingMinutes): add weekly update status 23-06-2022

docs/2022/atarashi/updates/2022-06-27.md
=> upadate(docs): Add week 3 update

docs/2022/reuse/updates/2022-06-20.md, docs/2022/reuse/updates/2022-06-27.md
=> docs(reuse): week 3 meeting update

docs/2022/spasht/index.md
updates Spasht Introduction file
Updated mail and LinkedIn id.
=> Updated GSOC docs in spasht project

docs/2022/minutes/23-06-2022.md, docs/2022/minutes/30-06-2022.md
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
GSOC22
Update meeting minutes for 30-06-2022
If there are any further notes.
=> feat(minutes): add meeting minutes for 30-06-2022

docs/2022/spasht/updates/2020-06-15, docs/2022/spasht/updates/2020-06-15.md
Added week2 update
Added Spasht weekly meeting details
=> Added week 2 updates

docs/2022/spasht/updates/2022-06-02.md
Updated meeting details in the Community bonding period file.
Updated details for 2 meetings
=> Updated community bonding period meeting details

docs/2022/spasht/updates/2022-06-22.md
Added week 3 update
Added Spasht weekly meeting details
=> Updated 2022-06-22.md

docs/2022/reuse/updates/2022-06-27.md, docs/2022/reuse/updates/2022-07-04.md
=> docs(reuse): added week 4 meeting update

docs/2022/atarashi/updates/2022-07-04.md
=> update(docs): Add week 4 update

docs/2022/spasht/updates/2022-07-06.md, docs/2022/spasht/updates/2022-07-13.md
Added week 4 and 5 updates
Added Spasht weekly meeting details
=> Added week 4 and 5 updates

docs/2022/atarashi/updates/2022-07-11.md
=> update(docs): Add week 5 update

docs/2022/reuse/updates/2022-07-18.md
=> docs(reuse): weekly update

docs/2022/reuse/updates/2022-07-25.md
=> docs(reuse): week 7 update added

docs/2022/atarashi/updates/2022-07-19.md
=> update(docs) Add week 6 update

docs/2022/reuse/updates/2022-08-02.md
=> docs(reuse): week 8 update

docs/2022/minutes/04-08-2022.md, docs/2022/minutes/11-08-2022.md, docs/2022/minutes/18-08-2022.md
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
Meeting Minutes.
Add meeting minutes for 4th, 11th and 18th august.
=> feat(minutes): add meeting minutes for 4th, 11th and 18th august

docs/2022/atarashi/updates/2022-07-26.md, docs/2022/atarashi/updates/2022-08-02.md
Atarashi
Added week 7 and week 8 updates
=> update(docs) Add week 7 and 8 updates

docs/2022/ui/updates/samuel/2021-06-24.md, docs/2022/ui/updates/samuel/2022-06-30.md, docs/2022/ui/updates/samuel/2022-07-07.md
Signed-off-by: dushimsam <dushsam@gmail.com>
Gsoc Weekly updates.
Renamed the titles for the existing files, giving them the proper names.
=> giving proper file titles.

docs/2022/reuse/updates/2022-08-09.md, docs/2022/reuse/updates/2022-08-16.md
=> docs(reuse); week 9-10 update

docs/2022/project/updates/2022-06-16.md, docs/2022/project/updates/2022-06-30.md, docs/2022/project/updates/2022-07-07.md, docs/2022/project/updates/2022-07-14.md, docs/2022/project/updates/2022-07-21.md, docs/2022/project/updates/2022-07-28.md, docs/2022/project/updates/2022-08-04.md, docs/2022/project/updates/2022-08-11.md, docs/2022/project/updates/2022-08-18.md
Add some blogs until 8.18
Add some blogs in docs/2022/project, the weekly blog has been updated util 8.18
None
=> Add some blogs until 8.18

docs/2022/reuse/updates/2022-08-23.md, docs/2022/reuse/updates/2022-08-30.md
=> docs(reuse); weekly update

docs/2022/minutes/25-08-2022.md
Signed-off-by: Shaheem Azmal M MD <shaheem.azmal@siemens.com>
=> feat(minutes): add meeting minutes for 25-08-2022

docs/2022/atarashi/updates/2022-08-09.md
=> update(docs) Add week 9 update

docs/2022/ui/updates/samuel/2022-08-02.md
Signed-off-by: dushimsam <dushsam@gmail.com>
Gsoc'22 Coding Period Updates.
Modified the report to be reflect on the contributions of Week 6 & 7.
=> Merged week 6 & 7

docs/2022/reuse/updates/2022-08-30.md, docs/2022/reuse/updates/2022-09-06.md
=> docs(reuse): week 12-13 update

docs/2022/project/updates/2022-08-25.md, docs/2022/project/updates/2022-09-01.md, docs/2022/project/updates/2022-09-08.md
Introduce concept of project in FOSSology
Add some blogs util Sep 8th.
=> Add some blogs util Sep 8th.

docs/2022/atarashi/updates/2022-08-16.md, docs/2022/atarashi/updates/2022-08-23.md, docs/2022/atarashi/updates/2022-08-30.md
Atarashi
Added weekly updated of week 10, 11 and 12
=> Added updates for week 10, 11 and 12

docs/guidelines/index.md, docusaurus.config.js
=> docs: contributor guidelines

docs/2023/copyrights/_category_.json, docs/2023/copyrights/index.md, docs/2023/copyrights/updates/2023-05-11.md, docs/2023/copyrights/updates/_category_.json, docs/2023/cyclonedx/_category_.json, docs/2023/cyclonedx/index.md, docs/2023/cyclonedx/updates/2023-05-11.md, docs/2023/cyclonedx/updates/_category_.json, docs/2023/index.md, docs/2023/laas/_category_.json, docs/2023/laas/index.md, docs/2023/laas/updates/2023-05-11.md, docs/2023/laas/updates/_category_.json, docs/2023/minutes/2023-05-11.md, docs/2023/minutes/_category_.json, docs/2023/rest/_category_.json, docs/2023/rest/index.md, docs/2023/rest/updates/_category_.json, docs/2023/rest/updates/samuel/2023-05-11.md, docs/2023/rest/updates/samuel/_category_.json, docs/2023/rest/updates/soham/_category_.json, docusaurus.config.js, package.json, yarn.lock
FOSSology
Setup new structure for 2023
=> docs(2023): setup structure for 2023

.github/workflows/deploy.yml, yarn.lock
Upgrade project dependencies to solve some vulnerabilities.
=> chore(dependencies): upgrade all dependencies

docs/2023/index.md, docs/2023/minutes/2023-05-11.md, static/ics/gsoc_2023_copyright.ics, static/ics/gsoc_2023_cyclonedx.ics, static/ics/gsoc_2023_laas.ics, static/ics/gsoc_2023_rest.ics, static/ics/gsoc_2023_weekly.ics
GSoC 2023
1. Add meeting minutes for first community bonding meeting.
2. Create meeting details and calendars.
=> docs(meetings): update meeting details for GSoC23

docs/2023/minutes/2023-05-18.md
Add meeting minutes for Community Bonding 2 (2023-05-18)
=> chore(minutes): community bonding updates 2

docs/2023/minutes/2023-05-25.md
General meeting minutes.
Added minutes for 2023-05-25
=> chore(minutes): community bonding3

docs/2023/laas/updates/2023-05-11.md
License as a service
Updates and discussions of community bonding period.
N/A
=> Updates and discussions of community bonding period.

docs/2023/rest/updates/samuel/2023-05-11.md
Gsoc'23 Report regarding the community bonding period.
Updated the existing file for detailed documentation.
=> report: updated the report regarding the community bonding

docs/2023/cyclonedx/updates/2023-05-11.md
Cyclonedx
Add updates for community bonding period
=> Add updates for community bonding period

docs/2023/laas/index.md
License as a Service
Added the basic information about the project in index.md.
=> docs: updated index.md

docs/2023/copyrights/index.md, docs/2023/copyrights/updates/2023-05-11.md, docs/2023/copyrights/updates/2023-05-31.md
Reducing false positive copyrights
- Updated the index.md and community bonding pages.
- Added the Week 1 updates to a new page.
=> Updated the index.md page, the community bonding page & Added the Week 1 updates.

docs/2023/minutes/2023-06-15.md
minutes
add minutes for general meeting on 2023-06-15
=> docs(meetings): add minutes from 2023-06-15

docs/2023/laas/index.md, docs/2023/laas/updates/2023-06-02.md, docs/2023/laas/updates/2023-06-09.md, docs/2023/laas/updates/2023-06-16.md
License as a service 
Added the report and minutes of first three weeks of coding period.
=> docs: update minutes of first three weeks of coding period.

docs/2023/laas/updates/2023-06-16.md, docs/2023/laas/updates/2023-06-23.md, docs/2023/laas/updates/2023-06-30.md, docs/2023/laas/updates/2023-07-07.md
License as a service
docs: updated 4th, 5th ,and 6th week meeting notes
=> docs: updated 4th, 5th ,and 6th week meeting notes

docs/2023/copyrights/updates/2023-06-28.md, docs/2023/copyrights/updates/2023-07-05.md, docs/2023/copyrights/updates/2023-07-12.md, docs/2023/copyrights/updates/2023-07-19.md
Reducing Fossology's false positive copyrights.
Added documentation for weeks 5, 6, 7, and 8.
=> Added updates for weeks 5, 6, 7, and 8.

docs/2023/laas/updates/2023-07-14.md, docs/2023/laas/updates/2023-07-21.md, docs/2023/laas/updates/2023-07-28.md, docs/2023/laas/updates/2023-08-04.md
License as a service
The blog for week 7,8,9 nd 10 is added.
=> docs: Added the updates, discussions and minutes of week 7,8,9,10

.github/workflows/deploy.yml, docs/2021/buildsystem/build.md, docs/2021/buildsystem/final-evaluation.md, docs/2021/copyrights/updates/2021-07-06.md, docs/2021/microservice/updates/2021-08-03.md, docs/2021/minerva/updates/2021-06-15.md, docs/2022/GSoC-projects.md, docs/2022/atarashi/updates/2022-06-20.md, docs/2022/ui/updates/krishna/2022-07-17.md, docs/2022/ui/updates/krishna/2022-08-14.md, docs/2022/ui/updates/krishna/2022-09-04.md, docs/2023/GSoC-projects.md, docs/2023/copyrights/updates/2023-09-13.md, docs/2023/copyrights/updates/2023-10-18.md, docusaurus.config.js, package.json, yarn.lock
=> deps(docu): upgrade to docusaurus 3.1

.github/workflows/deploy.yml, docs/2022/GSoC-projects.md, package.json, yarn.lock
Upgrade docusaurus from 3.1.0 to 3.3.2
=> feat(docu): upgrade docusaurus 3.1.0 to 3.3.2

docs/2024/minutes/2024-05-30.md
=> feat(minutes): add meeting notes from general updates

docs/2024/ci-scanner/updates/2024-06-06.md, docs/2024/ci-scanner/updates/2024-06-13.md
CI Scanner Improvements
Add @rajuljha 's coding period week 1 and week 2 reports for GSoC'24
=> chore(report): Add coding period week 1 and week 2 project reports

docs/2024/minutes/2024-06-06.md, docs/2024/minutes/2024-06-13.md, docs/2024/minutes/2024-06-20.md
Meeting Minutes
add meeting minutes for 6th, 13th and 20th june
=> feat(minutes): add meeting minutes for 6th, 13th and 20th june

docs/2024/minutes/2024-07-04.md
Minutes of the Meeting 04-07-2024
New Page according to meeting minutes.
=> Docs(minutes): Update Minutes of Meeting on 04072024

docs/2024/spdx-expression/updates/2024-06-25.md, static/reports/SPDX2TV_Test19.zip_1720209488.spdx, static/reports/SPDX2_Test19.zip_1720209507.spdx.rdf
SPDX Expression Support
- Added week 5 report.
=> chore(report): SPDX Expression week 5 report

docs/2024/scheduler/updates/2024-05-07.md, docs/2024/scheduler/updates/2024-05-09.md
- Update documentation of 07th May meeting.
- Update documentation of 09th May meeting.
=> Docs(meeting notes) update documentation of week-01 meeting.

docs/2024/pipeline/updates/2024-07-04.md
Data Pipeline
Added the Wiki report for Week 6.
=> chore(report): Data Pipeline Report Week6

docs/2024/scheduler/updates/Discussion/2024-06-14.md, docs/2024/scheduler/updates/Discussion/_category_.json, docs/2024/scheduler/updates/General/2024-06-13.md, docs/2024/scheduler/updates/General/_category_ .json
Update documentation of `13th June` meeting.
Update documentation of `14th June` meeting.
=> Docs(meeting notes) update documentation of week-06 meeting.

docs/2024/scheduler/updates/Discussion/2024-07-05.md, docs/2024/scheduler/updates/Discussion/_category_.json, docs/2024/scheduler/updates/General/2024-07-04.md, docs/2024/scheduler/updates/General/_category_ .json
Update documentation of `04th July` meeting.
Update documentation of `05th July` meeting.
=> Docs(meeting notes) update documentation of week-09 meeting.

docs/2024/license-detection/updates/2024-06-06.md, docs/2024/license-detection/updates/2024-06-13.md, docs/2024/license-detection/updates/2024-06-20.md, docs/2024/license-detection/updates/2024-06-27.md, docs/2024/license-detection/updates/2024-07-04.md, docs/2024/license-detection/updates/2024-07-11.md
AI Powered License Detection
Added the wiki reports for weeks 6 and 7.
=> chore(report): AI Powered License Detection Reports for Weeks 6 and 7

docs/2024/scheduler/updates/Discussion/2024-06-14.md
+ fixed markdown `syntax` for better organisation of documentation.
=> fix(readme) fixed syntax of documentation.

docs/2024/scheduler/updates/2024-05-23.md
Update documentation of `23rd May` meeting.
=> Docs(meeting notes) update documentation of week-03 meeting.

docs/2024/ci-scanner/updates/2024-07-18.md
Week 7 CI Scanner Project report @rajuljha 
* Add week 7 report
=> chore(report): Add week 7 report for CI Scanner project

docs/2024/rest/updates/Divij/2024-07-16.md
GSoC'24 week 8 report for REST API Improvements @dvjsharma.
=> chore(report): REST APIs week 8 report

docs/2024/scheduler/updates/Discussion/2024-06-21.md, docs/2024/scheduler/updates/General/2024-06-20.md
+ update the meeting count updated to prevent discrepancies.
=> Docs(meeting notes) updated General & Discussion of `week-07` meeting notes

docs/2024/scheduler/updates/Discussion/2024-06-28.md, docs/2024/scheduler/updates/General/2024-06-27.md
+ update the meeting count updated to prevent discrepancies.
=> Docs(meeting notes) updated General & Discussion of `week-08` meeting notes.

docs/2024/rest/updates/Divij/2024-07-30.md
GSoC'24 week 10 report for REST API Improvements @dvjsharma.
=> chore(report): REST APIs week 10 report

docs/2024/rest/updates/valens/2024-06-13.md, docs/2024/rest/updates/valens/2024-06-20.md, docs/2024/rest/updates/valens/2024-06-27.md, docs/2024/rest/updates/valens/2024-07-11.md, docs/2024/rest/updates/valens/2024-07-18.md
=> chore(report): REST API improvements week 7 report

package.json, yarn.lock
Update to Docusaurus 3.7.0 and prepare for v4
=> chore(docusaurus): update to 3.7.0

docs/2025/minutes/2025-06-05.md, docs/2025/minutes/2025-06-12.md, docs/2025/minutes/2025-06-19.md, docs/2025/minutes/2025-06-26.md, docs/2025/minutes/2025-07-03.md, docs/2025/minutes/2025-07-10.md, docs/2025/minutes/2025-07-17.md, docs/2025/minutes/2025-07-24.md, docs/2025/minutes/2025-07-31.md, docs/2025/minutes/2025-08-07.md, docs/2025/minutes/2025-08-14.md, docs/2025/minutes/2025-08-21.md, docs/2025/minutes/2025-08-28.md, docs/2025/minutes/2025-09-04.md, docs/2025/minutes/2025-09-11.md, docs/2025/minutes/2025-09-18.md, docs/2025/minutes/2025-09-25.md, docs/2025/minutes/2025-10-02.md, docs/2025/minutes/2025-10-09.md, docs/2025/minutes/2025-10-16.md, docs/2025/minutes/2025-10-23.md, docs/2025/minutes/2025-10-30.md, docs/2025/minutes/2025-11-06.md, docs/2025/minutes/2025-11-13.md, docs/2025/minutes/2025-11-20.md
Name of the project
What was updated (new pages, weekly update, etc.)
If there are any further notes.
=> chore(minutes): add meeting minutes template for all 2025 GSoC weeks

docs/2025/ui-react/index.md, docs/2025/ui-react/updates/2025-06-01.md, docs/2025/ui-react/updates/2025-06-07.md, docs/2025/ui-react/updates/_category_.json
FOSSology UI - React Completion 
- Added community bonding period updates.
- Added week 1 updates.
=> docs(ui-react): community bonding updates

docs/2025/atarashi-enhancement/index.md, docs/2025/atarashi-enhancement/updates/2025-05-29.md, docs/2025/atarashi-enhancement/updates/2025-06-04.md, docs/2025/atarashi-enhancement/updates/_category_.json
Enhance Atarashi's ability
Add reports for:
- Project description
- Community Bonding
- Week 1 report
=> chore(docs): Add Atarashi week1 report

docs/2025/licensedb-platform/index.md, docs/2025/licensedb-platform/updates/2025-05-30.md, docs/2025/licensedb-platform/updates/_category_.json
licensedb platform improvement
add bonding period report
=> chore(community_bonding): update the licensedb project details and bonding period report 

docs/2025/microservices-infrastructure/updates/2025-06-30.md
Complete Microservice Infrastructure for FOSSology
Added Week 4 report
=> chore(docs): Add Microservices project week4 report

docs/2025/text-phrases-bulk/updates/2025-06-24.md
Support text phrases and bulk based scanning for MONK a like agent 
Added updates for week 4
=> chore(docs): Add text-phrases-bulk week 4 report

docs/2025/minutes/2025-06-05.md, docs/2025/minutes/2025-06-12.md, docs/2025/minutes/2025-06-19.md, docs/2025/minutes/2025-06-26.md, docs/2025/minutes/2025-07-03.md, docs/2025/minutes/2025-07-10.md, docs/2025/minutes/2025-07-17.md, docs/2025/minutes/2025-07-24.md, docs/2025/minutes/2025-07-31.md, docs/2025/minutes/2025-08-07.md, docs/2025/minutes/2025-08-14.md, docs/2025/minutes/2025-08-21.md, docs/2025/minutes/2025-08-28.md, docs/2025/minutes/2025-09-04.md, docs/2025/minutes/2025-09-11.md, docs/2025/minutes/2025-09-18.md, docs/2025/minutes/2025-09-25.md, docs/2025/minutes/2025-10-02.md, docs/2025/minutes/2025-10-09.md, docs/2025/minutes/2025-10-16.md, docs/2025/minutes/2025-10-23.md, docs/2025/minutes/2025-10-30.md, docs/2025/minutes/2025-11-06.md, docs/2025/minutes/2025-11-13.md, docs/2025/minutes/2025-11-20.md
adding meeting notes for 26-06-2025 and 03-07-2025
=> feat(minutes): add meeting minutes for 26-06-2025 and 03-07-2025

package.json, yarn.lock
GSoC
Upgrade docusaurus and react versions
=> deps(docusaurus): upgrade docusaurus to 3.8

docs/2025/microservices-infrastructure/updates/2025-07-14.md
Complete Microservices Infrastructure of FOSSology
Add report of week 6
=> chore(docs): Add Microservices project week 6 report

docs/2025/debian-packaging/index.md, docs/2025/debian-packaging/updates/2025-07-03.md, docs/2025/debian-packaging/updates/2025-07-11.md, docs/2025/debian-packaging/updates/2025-07-17.md, docs/2025/debian-packaging/updates/_category_.json
Enhancing Debian Packaging for Fossology
- Updated the main project page for Debian packaging
- Added community bonding period report
- Added week 1 and week 2 reports
- Improved documentation structure and clarity
=> chore(docs): update Debian packaging project docs

docs/2025/minutes/2025-07-10.md, docs/2025/minutes/2025-07-17.md
=> chore(docs): add meeting minutes for 10th and 17th july

docs/2025/licensedb-platform/updates/2025-07-14.md, docs/2025/licensedb-platform/updates/2025-07-21.md, docs/2025/licensedb-platform/updates/2025-07-28.md
Licensed platefrom improvements
weekly report week 7,8 &9
=> chore(report): weekly report week 7 ,8 &9 

docs/2025/debian-packaging/updates/2025-08-16.md
Enhanced Debian Packaging for FOSSology
- Resolve critical autoloader integration issues for web interface
- Implement configuration automation in package build process
- Automate database setup and user creation in postinst script
- Create comprehensive PSR-4 autoloader in php-psr-log package
- Enhance fossology.conf.in with all required sections
- Achieve fully functional and production-ready FOSSology package
- Transform manually-configured system into automated Debian package
This update covers the successful transformation of FOSSology from a manually-configured system into a fully automated, self-contained Debian package. Key achievements include resolving critical autoloader integration issues, implementing configuration automation, and achieving production-ready status with …
=> chore(docs): add week 5 report for Debian packaging project

docs/2025/microservices-infrastructure/updates/2025-08-25.md
Complete Microservices Infrastructure of FOSSology
Added week12 report
=> chore(docs):Add Microservices project week 12 report

docs/2025/microservices-infrastructure/updates/2025-09-01.md
Complete Microservices Infrastructure of FOSSology
Added week 13 Report
=> chore(docs):Add Microservices project week 13 report

docs/2025/osselot/updates/2025-08-19.md, docs/2025/osselot/updates/2025-08-26.md, docs/2025/osselot/updates/2025-09-01.md, docs/2025/osselot/updates/2025-09-08.md, docs/2025/osselot/updates/2025-09-15.md
Reuse of clearing decisions using reports from OSSelot project.
Added week 11 to 15 reports.
=> chore(docs): weekly report week 11 to 15
