- src/components/ParticipantImages.js
- src/components/ParticipantImages.module.css
- src/pages/index.module.css
Style enhancement as mentioned in #32 
- Fix button oveflow in homescreen
- In the current home screen, the about buttons of 2020 and 2021 projects overflow the screen in small devices
- Added flex direction for small screen to solve this issue
- Changed style for Crousel image caption
- Added padding in Image crousel title
- Footer links is not centred in this PR
Closes #32
> Style enhancements, solving problems mentioned in issue #32

- docs/2023/cyclonedx/updates/2023-07-13.md
- docs/2023/cyclonedx/updates/2023-07-20.md
- docs/2023/cyclonedx/updates/2023-07-27.md
- docs/2023/cyclonedx/updates/2023-08-03.md
- docs/2023/cyclonedx/updates/2023-08-10.md
CycloneDX
Updates of week 7 to week 11
> Add updates for week 7 to week 11

- docs/2024/rest/updates/2024-06-06.md
GSoC'24 week 2 report for REST API Improvements @dvjsharma
> chore(report): REST APIs week 2 report

- docs/2024/rest/updates/valens/2024-06-27.md
- docs/2024/rest/updates/valens/2024-07-04.md
REST API improvements
- Added a new file holding my updates for week 5.
> chore(report):  report for week 5

- docs/2024/scheduler/updates/Discussion/2024-06-21.md
- docs/2024/scheduler/updates/Discussion/_category_.json
- docs/2024/scheduler/updates/General/2024-06-20.md
- docs/2024/scheduler/updates/General/_category_ .json
Update documentation of `20th July` meeting.
Update documentation of `21st July` meeting.
> Docs(meeting notes) update documentation of week-07 meeting.

- docs/2024/rest/updates/Divij/2024-07-09.md
GSoC'24 week 7 report for REST API Improvements @dvjsharma.
> chore(report): REST APIs week 7 report

- docs/2024/scheduler/updates/Discussion/2024-07-12.md
- docs/2024/scheduler/updates/General/2024-07-11.md
+ update documentation of `11th July` meeting.
+ update documentation of `12th July` meeting.
> docs(meeting notes) update documentation of week-10 meetings.

- docs/2024/ci-scanner/updates/2024-07-25.md
CI Scanner Project
Add week 8 project report for CI Scanner project @rajuljha
> chore(report): Add week 8 CI Scanner Project Report

- docs/2024/rest/updates/Divij/2024-07-23.md
GSoC'24 week 9 report for REST API Improvements @dvjsharma.
> chore(report): REST APIs week 9 report

- docs/2024/ci-scanner/updates/2024-08-15.md
CI Scanner Week 11 Report @rajuljha 
Add week 11 report file
> chore(report): Add week 11 CI Scanner report

- docs/2024/rest/updates/Divij/2024-08-06.md
GSoC'24 week 11 report for REST API Improvements @dvjsharma.
> chore(report): REST APIs week 11 report

- docs/2024/rest/updates/Divij/2024-08-16.md
GSoC'24 week 12 report for REST API Improvements @dvjsharma.
> chore(report): REST APIs week 12 report

- docs/2024/license-detection/updates/2024-05-30.md
- docs/2024/license-detection/updates/2024-06-06.md
- docs/2024/license-detection/updates/2024-06-13.md
- docs/2024/license-detection/updates/2024-06-20.md
- docs/2024/license-detection/updates/2024-06-27.md
- docs/2024/license-detection/updates/2024-07-04.md
- docs/2024/license-detection/updates/2024-07-11.md
- docs/2024/license-detection/updates/2024-07-18.md
- docs/2024/license-detection/updates/2024-07-25.md
- docs/2024/license-detection/updates/2024-08-01.md
- docs/2024/license-detection/updates/2024-08-08.md
- docs/2024/license-detection/updates/2024-08-15.md
- docs/2024/license-detection/updates/2024-08-22.md
- docs/2024/license-detection/updates/2024-08-29.md
- docs/2024/license-detection/updates/2024-09-05.md
Project
AI Powered License Detection
Changes
Added the wiki reports for weeks 8 to 15.
> chore(report): AI Powered License Detection Reports for weeks 8-15

- docs/2024/rest/updates/valens/2024-06-27.md
- docs/2024/rest/updates/valens/2024-07-04.md
- docs/2024/rest/updates/valens/2024-07-11.md
- docs/2024/rest/updates/valens/2024-07-18.md
- docs/2024/rest/updates/valens/2024-07-26.md
- docs/2024/rest/updates/valens/2024-08-16.md
- docs/2024/rest/updates/valens/2024-08-23.md
- docs/2024/rest/updates/valens/2024-08-30.md
- docs/2024/rest/updates/valens/2024-09-06.md
- docs/2024/rest/updates/valens/2024-09-13.md
GSoC week 8-12 report for REST API Improvements.
- I have changed the URLs to pull requests in previous weeks
- I have added the report for 8th  up to 12th week.
> chore(report): REST APIs week 8-12 report

- docs/2025/microservices-infrastructure/2025-06-02.md
- docs/2025/microservices-infrastructure/index.md
Complete Microservices Infrastructure for FOSSology
- dded introduction and project details documentation
- Added Community Bonding Period report
- Documented meetings, mentor interactions, and setup progress
> chore(report): Community bonding period report

- docs/2025/ux-ui-design/index.md
Redesign of UI/UX For FOSSology
Added introduction page to project.
cc: @Kaushl2208 @GMishx
> docs(uiux): update introduction page for ui-ux project

- docs/2025/microservices-infrastructure/updates/2025-06-02.md
- docs/2025/microservices-infrastructure/updates/2025-06-06.md
- docs/2025/microservices-infrastructure/updates/_category_.json
Complete Microservices Infrastructure for FOSSology
Added Week 1 report
> chore(docs): Add Microservices project week1 report

- docs/2025/licensedb-platform/updates/2025-06-05.md
licensedb improvements
week1 updates
> chore(docs): week 1 updates for licensedb improvements

- docs/2025/ui-react/updates/2025-06-01.md
- docs/2025/ui-react/updates/2025-06-07.md
- docs/2025/ui-react/updates/2025-06-14.md
- docs/2025/ui-react/updates/2025-06-21.md
FOSSology UI - React Completion
- Minor changes to previous updates.
- Added week 2 & 3 updates.
> docs(ui-react): weekly updates

- docs/2025/licensedb-platform/updates/2025-06-12.md
licensedb platform improvement
weekly repoort
> docs(week2):weekly report licensedb improvement

- docs/2025/licensedb-platform/updates/2025-06-19.md
Licensed Platform Improvement
weekly report
If there are any further notes.
> docs(week3):weekly report licensedb improvement

- docs/2025/licensedb-platform/updates/2025-06-24.md
- docs/2025/licensedb-platform/updates/2025-06-31.md
- docs/2025/licensedb-platform/updates/2025-07-07.md
licensedb platform improvements
weekly report for week 4,5&6
> chore(docs):weekly report week 4 , 5 and 6

- docs/2025/debian-packaging/updates/2025-08-02.md
Debian packaging for Fossology
Added Week 3 report for the Debian packaging project
Documented packaging of 20+ additional PHP libraries with ITP filings
Updated progress on FOSSology build system modernization (CMake migration, dependency cleanup)
Added details on Docker environment testing and version pinning solutions
Included comprehensive list of 19 new PHP packages created this week with their corresponding ITP links
> chore(docs): add week 3 report for Debian packaging project

- docs/2025/microservices-infrastructure/updates/2025-07-28.md
Complete Microservices Infrastructure of FOSSology
Added week 8 report
> chore(docs): Add Microservices Project week 8 report

- docs/2025/atarashi-enhancement/updates/2025-07-16.md
- docs/2025/atarashi-enhancement/updates/2025-08-13.md
- docs/2025/atarashi-enhancement/updates/2025-08-20.md
- docs/2025/atarashi-enhancement/updates/2025-08-27.md
Enhance Atarashi's ability
Add week 11, 12, 13 reports for Atarashi
> chore(docs): Add week 11,12,13 reports Atarashi
